### ISSUE TITLE
electron-updater marked as deprecated

### ISSUE THREAD

**Issue by skellock** [skellock/electron-starter#85]
@rmevans9 was mentioning that `electron-updater` is now deprecated.  This is coming in from `electron-builder`.  

Let's find out the scoop before shipping 1.0.

**Comment by rmevans9** [comment]
ref: https://github.com/develar/electron-updater

**Comment by skellock** [comment]
Wait, I'm a liar.

We've got a [dependency](https://github.com/skellock/electron-starter/blob/master/package.json#L48) on `electron-updater`.

And in `electron-builder` [doesn't](https://github.com/electron-userland/electron-builder/blob/master/package.json).

Care to comment @skellock? 😊

**Comment by rmevans9** [comment]
I believe this is not actually a bug...

Electron Updater lives here:
https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater

NPM Points to electron-builder github:
https://www.npmjs.com/package/electron-updater

The note clearly states that since 1.0.0 it has been a part of electron-builder:
https://github.com/develar/electron-updater#note

I think this can be closed as a non-issue

**Comment by skellock** [comment]
Thx.  Ya everything seems to indicate it is fine.  Where did you see that it was deprecated?

**Comment by rmevans9** [comment]
The title in the github repo that is/was used specifically for it:

https://github.com/develar/electron-updater (right at the top)

**Comment by skellock** [comment]
Ahh.  Gotcha.  Ok, that is now hosted in the builder monorepo.

Ok, cool.  Good sleuthing.
